services:

  postgres:
    image: 'postgres:latest'

    environment:
      - 'POSTGRES_DB=springboot_personal'
      - 'POSTGRES_PASSWORD=a1b2c3d4'
      - 'POSTGRES_USER=devdb'
    ports:
      - "5433:5433"

    networks:
      - red-backend-app

  demo:

    image: 'pedrodqt/demo:latest'
    ports:
      - '8080:8080'
    depends_on:
        - postgres
    environment:
      DB_URL: jdbc:postgresql://3.148.173.213:5432/Springboot_personal
      DB_USERNAME: devdb
      DB_PASSWORD: a1b2c3d4
      JPA_DDL: create-drop
    profiles:
      - app
    networks:
      - red-backend-app

networks:
  red-backend-app:
    driver: bridge